name: example
description: Example using Flutter Duration Picker

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_duration_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.9.0 <4.0.0'

flutter:
  uses-material-design: true
