name: flutter_duration_picker
description: A widget for picking durations, inspired by Material Time Picker.
version: 1.0.4
author: M.K. Malik (forked from Chris Harris <c@harrischris.com>  https://github.com/cdharris/flutter_duration_picker)
homepage: https://github.com/MKMalik/flutter_duration_picker.git
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
